// ─── Language strings for GymSystem Bot ─────────────────────
// Languages: uz (O'zbekcha), ru (Русский), kk (Қазақша), en (English)

const uz = {
  welcome: `<b>Xush kelibsiz!</b>\nGymSystem zaliga qatnashish uchun ro'yxatdan o'ting.\n\nIltimos, pastdagi tugmani bosib telefon raqamingizni yuboring.`,
  sharePhoneBtn: '📞 Raqamni yuborish',
  registered: (name) => `✅ <b>Ajoyib, ${name}!</b> Siz muvaffaqiyatli ro'yxatdan o'tdingiz.\n\nHozirda abonementingiz yo'q. Quyidagi menyudan foydalanib abonement sotib oling.`,
  menuCode: '🔑 Kirish kodi', menuQr: '🎫 QR Pass olish', menuAccount: '📊 Mening hisobim', menuHistory: '📅 Tashriflar tarixi',
  entryCodeMsg: (code, left, name) => `🔑 <b>Kirish kodingiz:</b>\n\n<code>${code}</code>\n\n👤 ${name}\n⏳ Qolgan: ${left} kun\n\n<i>Bu kod faqat bugun amal qiladi.\nKodni menejerga ayting yoki kioskda kiriting.</i>`,
  menuBuy: '💳 Abonement sotib olish', menuContact: '📞 Aloqa', menuRefresh: '🔄 Yangilash',
  menuLang: '🌐 Til / Language', menuScan: '📸 QR orqali kirish',
  scanWrongGym: (got, expected) => `❌ Bu QR boshqa zalga (@${got}). Sizdagi @${expected} botiga tegishli QR ni skanerlang.`,
  scanInvalid: '❌ QR mos kelmadi. Devordagi check-in QR ni skaner qiling.',
  mainMenuGreeting: (name) => `Salom, <b>${name}</b>! 👋`,
  mainMenuSub: (left, total) => `Abonement: <b>${left} / ${total} mashg'ulot kuni</b>`,
  mainMenuPlan: (plan) => `🏅 Plan: <b>${plan}</b>`,
  mainMenuExpired: '🔴 <i>Abonementingiz tugagan!</i>',
  mainMenuWarning: (left) => `⚠️ <i>Diqqat! Faqat ${left} kun qoldi!</i>`,
  mainMenuChoose: 'Kerakli bo\'limni tanlang:',
  qrExpired: `🔴 <b>Abonement tugagan!</b>\n\nZal kirishiga ruxsat yo'q.\nIltimos, yangi abonement sotib oling.`,
  qrBuyBtn: '💳 Abonement sotib olish',
  qrCaption: (name, left, plan) => `🎫 <b>${name}ning QR Passi</b>\n\n` + `Qolgan: <b>${left} mashg'ulot kuni</b>\n🏅 Plan: <b>${plan}</b>\n\n⏱ <i>QR kod 5 daqiqa amal qiladi.\nSkaner oldiga tuzing.</i>`,
  accountTitle: '📊 <b>Sizning profilingiz</b>',
  accountName: (name) => `👤 Ism: <b>${name}</b>`, accountPlan: (plan) => `🏅 Plan: <b>${plan}</b>`,
  accountTotal: (total) => `📦 Jami abonement: <b>${total} kun</b>`,
  accountUsed: (used) => `✔️ O'tilgan: <b>${used} ta</b>`, accountLeft: (left) => `⏳ Qolgan: <b>${left} ta</b>`,
  accountStatusActive: 'Faol', accountStatusExpired: 'Tugagan',
  accountStatus: (emoji, text) => `${emoji} Holat: <b>${text}</b>`,
  historyTitle: '📅 <b>Tashriflar tarixi</b>',
  historyEmpty: "<i>Hali tashrif yo'q.\nBirinchi mashg'ulotingizni boshlang! 💪</i>",
  historyTotal: (n) => `✔️ Jami tashriflar: <b>${n} ta</b>`,
  historyDaysLeft: (left) => `⏳ Qolgan kunlar: <b>${left} ta</b>`,
  buyTitle: '💳 <b>Abonement sotib olish</b>',
  buyEmpty: '💳 <b>Abonement sotib olish</b>\n\nHozircha hech qanday tarif mavjud emas.',
  buyChoose: 'Planni tanlang:', buyDays: 'kun',
  payTitle: '💳 <b>To\'lov</b>', payPlan: 'Plan',
  payDuration: (days) => `📅 Muddat: <b>${days} mashg'ulot kuni</b>`,
  payPrice: (price) => `💰 Narx: <b>${price}</b>`,
  payChooseMethod: 'To\'lov usulini tanlang:',
  payCash: '💸 Naqd to\'lov qildim', payOnline: '💳 Online to\'lov qildim (Payme/Click)',
  payBack: '◀️ Orqaga', payPlanNotFound: 'Bu tarif topilmadi.',
  cashCreated: (refId) => `✅ <b>So'rov #${refId} qabul qilindi!</b>\n\nAdministrator tekshirib tasdiqlaydi.\nNatija haqida xabar beramiz.`,
  onlineInstructions: (planName, price, gymName) => `💳 <b>Online to'lov</b>\n\n📦 ${planName} — <b>${price}</b>\n\nTo'lov usullari:\n💚 Payme — ilovadan to'lang\n🔵 Click — ilovadan to'lang\n\nSumma: <b>${price}</b>\nQabul qiluvchi: <b>${gymName}</b>\n\n⬇️ <b>To'lovdan keyin chek rasmini shu chatga yuboring!</b>`,
  receiptReceived: (refId) => `✅ <b>Chek qabul qilindi!</b>\n\nSo'rov raqami: <b>#${refId}</b>\nAdministrator tekshirib tasdiqlaydi.\nNatija haqida xabar beramiz.`,
  sendReceipt: 'To\'lovdan keyin chek rasmini yuboring',
  adminNewPayment: '💰 <b>Yangi To\'lov So\'rovi</b>',
  adminMember: (name) => `👤 A'zo: <b>${name}</b>`, adminPhone: (phone) => `📞 Tel: <b>${phone}</b>`,
  adminPlan: (emoji, name) => `${emoji} Plan: <b>${name}</b>`, adminPrice: (price) => `💰 Narx: <b>${price}</b>`,
  adminDays: (days) => `📅 Kun: <b>${days}</b>`, adminConfirmQ: 'Tasdiqlaysizmi?',
  adminApproveBtn: '✅ Tasdiqlash', adminRejectBtn: '❌ Rad etish',
  adminNotAdmin: 'Siz admin emassiz!', adminNotFound: 'Topilmadi',
  adminAlreadyApproved: 'Allaqachon tasdiqlangan!', adminApproved: 'Tasdiqlandi!',
  adminApprovedMsg: (days) => `✅ To'lov tasdiqlandi! ${days} kun qo'shildi.`,
  adminAlreadyProcessed: 'Allaqachon ko\'rib chiqilgan', adminRejected: 'Rad etildi',
  adminRejectedMsg: '❌ To\'lov rad etildi.',
  memberApproved: (name, days) => `🎉 <b>Tabriklaymiz, ${name}!</b>\n\nTo'lovingiz admin tomonidan tasdiqlandi.\nHisobingizga <b>${days} kun</b> qo'shildi.\nEndi asosiy menyudan QR Pass olishingiz mumkin!`,
  memberRejected: `⚠️ <b>To'lov rad etildi!</b>\nAdmin to'lovingizni bekor qildi. Iltimos, qayta urinib ko'ring yoki administrator bilan bog'laning.`,
  contactTitle: '📞 <b>Aloqa ma\'lumotlari</b>', contactHours: 'Ish vaqti:',
  contactWeekdays: '⏰ Dushanba – Shanba: 07:00 – 22:00', contactSunday: '⏰ Yakshanba: Dam olish kuni',
  contactTelegram: (user) => `📱 Telegram: ${user}`, contactPhone: (phone) => `📞 Telefon: ${phone}`,
  contactNote: 'Savollaringiz bo\'lsa, doim yozishingiz mumkin!', contactWriteBtn: '📱 Yozish',
  notRegisteredCb: "Ro'yxatdan o'tmagansiz. /start ni bosing",
  notRegisteredText: "Iltimos, avval /start buyrug'ini yuboring va ro'yxatdan o'ting.",
  fallback: '👋 Quyidagi tugmalardan foydalaning:',
  langSwitchPrompt: '🌐 <b>Tilni tanlang:</b>',
  langSwitchUz: '🇺🇿 O\'zbekcha', langSwitchRu: '🇷🇺 Русский',
  langSwitchKk: '🇰🇿 Қазақша', langSwitchEn: '🇬🇧 English',
  langSwitched: '✅ Til: O\'zbekcha',
  frozenMsg: '❄️ Abonementingiz muzlatilgan. Menejerga murojaat qiling.',
};

const ru = {
  welcome: `<b>Добро пожаловать!</b>\nДля посещения зала GymSystem необходима регистрация.\n\nПожалуйста, нажмите кнопку ниже и отправьте свой номер телефона.`,
  sharePhoneBtn: '📞 Отправить номер',
  registered: (name) => `✅ <b>Отлично, ${name}!</b> Вы успешно зарегистрировались.\n\nУ вас пока нет абонемента. Приобретите его через меню ниже.`,
  menuCode: '🔑 Код входа', menuQr: '🎫 Получить QR Pass', menuAccount: '📊 Мой аккаунт', menuHistory: '📅 История посещений',
  entryCodeMsg: (code, left, name) => `🔑 <b>Ваш код входа:</b>\n\n<code>${code}</code>\n\n👤 ${name}\n⏳ Осталось: ${left} дней\n\n<i>Код действителен только сегодня.\nСообщите его менеджеру или введите на киоске.</i>`,
  menuBuy: '💳 Купить абонемент', menuContact: '📞 Контакты', menuRefresh: '🔄 Обновить',
  menuLang: '🌐 Til / Language', menuScan: '📸 Войти по QR',
  scanWrongGym: (got, expected) => `❌ QR другого зала (@${got}). Сканируйте QR бота @${expected}.`,
  scanInvalid: '❌ QR не подходит. Сканируйте QR check-in на стене.',
  mainMenuGreeting: (name) => `Привет, <b>${name}</b>! 👋`,
  mainMenuSub: (left, total) => `Абонемент: <b>${left} / ${total} тренировочных дней</b>`,
  mainMenuPlan: (plan) => `🏅 Тариф: <b>${plan}</b>`,
  mainMenuExpired: '🔴 <i>Ваш абонемент истёк!</i>',
  mainMenuWarning: (left) => `⚠️ <i>Внимание! Осталось всего ${left} дней!</i>`,
  mainMenuChoose: 'Выберите нужный раздел:',
  qrExpired: `🔴 <b>Абонемент истёк!</b>\n\nДоступ в зал закрыт.\nПожалуйста, приобретите новый абонемент.`,
  qrBuyBtn: '💳 Купить абонемент',
  qrCaption: (name, left, plan) => `🎫 <b>QR Pass — ${name}</b>\n\nОсталось: <b>${left} тренировочных дней</b>\n🏅 Тариф: <b>${plan}</b>\n\n⏱ <i>QR-код действителен 5 минут.\nПоднесите к сканеру.</i>`,
  accountTitle: '📊 <b>Ваш профиль</b>',
  accountName: (name) => `👤 Имя: <b>${name}</b>`, accountPlan: (plan) => `🏅 Тариф: <b>${plan}</b>`,
  accountTotal: (total) => `📦 Всего абонемент: <b>${total} дней</b>`,
  accountUsed: (used) => `✔️ Использовано: <b>${used}</b>`, accountLeft: (left) => `⏳ Осталось: <b>${left}</b>`,
  accountStatusActive: 'Активен', accountStatusExpired: 'Истёк',
  accountStatus: (emoji, text) => `${emoji} Статус: <b>${text}</b>`,
  historyTitle: '📅 <b>История посещений</b>',
  historyEmpty: '<i>Посещений пока нет.\nНачните свою первую тренировку! 💪</i>',
  historyTotal: (n) => `✔️ Всего посещений: <b>${n}</b>`,
  historyDaysLeft: (left) => `⏳ Осталось дней: <b>${left}</b>`,
  buyTitle: '💳 <b>Купить абонемент</b>',
  buyEmpty: '💳 <b>Купить абонемент</b>\n\nНа данный момент тарифы недоступны.',
  buyChoose: 'Выберите тариф:', buyDays: 'дней',
  payTitle: '💳 <b>Оплата</b>', payPlan: 'Тариф',
  payDuration: (days) => `📅 Срок: <b>${days} тренировочных дней</b>`,
  payPrice: (price) => `💰 Цена: <b>${price}</b>`,
  payChooseMethod: 'Выберите способ оплаты:',
  payCash: '💸 Оплатил наличными', payOnline: '💳 Оплатил онлайн (Payme/Click)',
  payBack: '◀️ Назад', payPlanNotFound: 'Тариф не найден.',
  cashCreated: (refId) => `✅ <b>Запрос #${refId} принят!</b>\n\nАдминистратор проверит и подтвердит.\nМы сообщим вам о результате.`,
  onlineInstructions: (planName, price, gymName) => `💳 <b>Онлайн оплата</b>\n\n📦 ${planName} — <b>${price}</b>\n\nСпособы оплаты:\n💚 Payme — оплатите через приложение\n🔵 Click — оплатите через приложение\n\nСумма: <b>${price}</b>\nПолучатель: <b>${gymName}</b>\n\n⬇️ <b>После оплаты отправьте фото чека в этот чат!</b>`,
  receiptReceived: (refId) => `✅ <b>Чек получен!</b>\n\nНомер запроса: <b>#${refId}</b>\nАдминистратор проверит и подтвердит.\nМы сообщим вам о результате.`,
  sendReceipt: 'После оплаты отправьте фото чека',
  adminNewPayment: '💰 <b>Новый запрос на оплату</b>',
  adminMember: (name) => `👤 Участник: <b>${name}</b>`, adminPhone: (phone) => `📞 Тел: <b>${phone}</b>`,
  adminPlan: (emoji, name) => `${emoji} Тариф: <b>${name}</b>`, adminPrice: (price) => `💰 Цена: <b>${price}</b>`,
  adminDays: (days) => `📅 Дней: <b>${days}</b>`, adminConfirmQ: 'Подтверждаете?',
  adminApproveBtn: '✅ Подтвердить', adminRejectBtn: '❌ Отклонить',
  adminNotAdmin: 'Вы не администратор!', adminNotFound: 'Не найдено',
  adminAlreadyApproved: 'Уже подтверждено!', adminApproved: 'Подтверждено!',
  adminApprovedMsg: (days) => `✅ Оплата подтверждена! ${days} дней добавлено.`,
  adminAlreadyProcessed: 'Уже обработано', adminRejected: 'Отклонено',
  adminRejectedMsg: '❌ Оплата отклонена.',
  memberApproved: (name, days) => `🎉 <b>Поздравляем, ${name}!</b>\n\nВаша оплата подтверждена администратором.\nНа ваш счёт добавлено <b>${days} дней</b>.\nТеперь вы можете получить QR Pass в главном меню!`,
  memberRejected: `⚠️ <b>Оплата отклонена!</b>\nАдминистратор отклонил вашу оплату. Пожалуйста, попробуйте снова или свяжитесь с администратором.`,
  contactTitle: '📞 <b>Контактная информация</b>', contactHours: 'Часы работы:',
  contactWeekdays: '⏰ Понедельник – Суббота: 07:00 – 22:00', contactSunday: '⏰ Воскресенье: Выходной',
  contactTelegram: (user) => `📱 Telegram: ${user}`, contactPhone: (phone) => `📞 Телефон: ${phone}`,
  contactNote: 'Если у вас есть вопросы, пишите нам в любое время!', contactWriteBtn: '📱 Написать',
  notRegisteredCb: 'Вы не зарегистрированы. Нажмите /start',
  notRegisteredText: 'Пожалуйста, сначала отправьте команду /start и зарегистрируйтесь.',
  fallback: '👋 Используйте кнопки меню ниже:',
  langSwitchPrompt: '🌐 <b>Tilni tanlang:</b>',
  langSwitchUz: '🇺🇿 O\'zbekcha', langSwitchRu: '🇷🇺 Русский',
  langSwitchKk: '🇰🇿 Қазақша', langSwitchEn: '🇬🇧 English',
  langSwitched: '✅ Язык: Русский',
  frozenMsg: '❄️ Ваш абонемент заморожен. Обратитесь к менеджеру.',
};

const kk = {
  welcome: `<b>Қош келдіңіз!</b>\nGymSystem залына қатысу үшін тіркеліңіз.\n\nТөмендегі түймені басып телефон нөміріңізді жіберіңіз.`,
  sharePhoneBtn: '📞 Нөмірді жіберу',
  registered: (name) => `✅ <b>Тамаша, ${name}!</b> Сіз сәтті тіркелдіңіз.\n\nҚазір абонементіңіз жоқ. Төмендегі мәзірден абонемент сатып алыңыз.`,
  menuCode: '🔑 Кіру коды', menuQr: '🎫 QR Pass алу', menuAccount: '📊 Менің аккаунтым', menuHistory: '📅 Кіру тарихы',
  entryCodeMsg: (code, left, name) => `🔑 <b>Кіру кодыңыз:</b>\n\n<code>${code}</code>\n\n👤 ${name}\n⏳ Қалған: ${left} күн\n\n<i>Код тек бүгін жарамды.\nМенеджерге айтыңыз немесе киоскте еңгізіңіз.</i>`,
  menuBuy: '💳 Абонемент сатып алу', menuContact: '📞 Байланыс', menuRefresh: '🔄 Жаңарту',
  menuLang: '🌐 Til / Language', menuScan: '📸 QR арқылы кіру',
  scanWrongGym: (got, expected) => `❌ Бұл QR басқа залдікі (@${got}). Сіздің @${expected} ботыңыздың QR-ын сканерлеңіз.`,
  scanInvalid: '❌ QR сәйкес келмеді. Қабырғадағы QR-ды сканерлеңіз.',
  mainMenuGreeting: (name) => `Сәлем, <b>${name}</b>! 👋`,
  mainMenuSub: (left, total) => `Абонемент: <b>${left} / ${total} жаттығу күні</b>`,
  mainMenuPlan: (plan) => `🏅 Тариф: <b>${plan}</b>`,
  mainMenuExpired: '🔴 <i>Абонементіңіздің мерзімі біткен!</i>',
  mainMenuWarning: (left) => `⚠️ <i>Назар аударыңыз! Тек ${left} күн қалды!</i>`,
  mainMenuChoose: 'Қажетті бөлімді таңдаңыз:',
  qrExpired: `🔴 <b>Абонемент мерзімі біткен!</b>\n\nЗалға кіруге рұқсат жоқ.\nЖаңа абонемент сатып алыңыз.`,
  qrBuyBtn: '💳 Абонемент сатып алу',
  qrCaption: (name, left, plan) => `🎫 <b>${name} QR Pass</b>\n\nҚалған: <b>${left} жаттығу күні</b>\n🏅 Тариф: <b>${plan}</b>\n\n⏱ <i>QR код 5 минут жарамды.\nСканерге көрсетіңіз.</i>`,
  accountTitle: '📊 <b>Сіздің профиліңіз</b>',
  accountName: (name) => `👤 Аты: <b>${name}</b>`, accountPlan: (plan) => `🏅 Тариф: <b>${plan}</b>`,
  accountTotal: (total) => `📦 Жалпы абонемент: <b>${total} күн</b>`,
  accountUsed: (used) => `✔️ Пайдаланылған: <b>${used}</b>`, accountLeft: (left) => `⏳ Қалған: <b>${left}</b>`,
  accountStatusActive: 'Белсенді', accountStatusExpired: 'Мерзімі біткен',
  accountStatus: (emoji, text) => `${emoji} Күйі: <b>${text}</b>`,
  historyTitle: '📅 <b>Кіру тарихы</b>',
  historyEmpty: '<i>Әзірге кіру жоқ.\nБірінші жаттығуыңызды бастаңыз! 💪</i>',
  historyTotal: (n) => `✔️ Жалпы кірулер: <b>${n}</b>`,
  historyDaysLeft: (left) => `⏳ Қалған күндер: <b>${left}</b>`,
  buyTitle: '💳 <b>Абонемент сатып алу</b>',
  buyEmpty: '💳 <b>Абонемент сатып алу</b>\n\nҚазір тарифтер жоқ.',
  buyChoose: 'Тарифті таңдаңыз:', buyDays: 'күн',
  payTitle: '💳 <b>Төлем</b>', payPlan: 'Тариф',
  payDuration: (days) => `📅 Мерзімі: <b>${days} жаттығу күні</b>`,
  payPrice: (price) => `💰 Бағасы: <b>${price}</b>`,
  payChooseMethod: 'Төлем әдісін таңдаңыз:',
  payCash: '💸 Қолма-қол төледім', payOnline: '💳 Онлайн төледім (Payme/Click)',
  payBack: '◀️ Артқа', payPlanNotFound: 'Тариф табылмады.',
  cashCreated: (refId) => `✅ <b>Сұраныс #${refId} қабылданды!</b>\n\nӘкімші тексеріп растайды.\nНәтиже туралы хабарлаймыз.`,
  onlineInstructions: (planName, price, gymName) => `💳 <b>Онлайн төлем</b>\n\n📦 ${planName} — <b>${price}</b>\n\nТөлем әдістері:\n💚 Payme — қосымшадан төлеңіз\n🔵 Click — қосымшадан төлеңіз\n\nСома: <b>${price}</b>\nАлушы: <b>${gymName}</b>\n\n⬇️ <b>Төлемнен кейін чек суретін осы чатқа жіберіңіз!</b>`,
  receiptReceived: (refId) => `✅ <b>Чек қабылданды!</b>\n\nСұраныс нөмірі: <b>#${refId}</b>\nӘкімші тексеріп растайды.\nНәтиже туралы хабарлаймыз.`,
  sendReceipt: 'Төлемнен кейін чек суретін жіберіңіз',
  adminNewPayment: '💰 <b>Жаңа төлем сұранысы</b>',
  adminMember: (name) => `👤 Қатысушы: <b>${name}</b>`, adminPhone: (phone) => `📞 Тел: <b>${phone}</b>`,
  adminPlan: (emoji, name) => `${emoji} Тариф: <b>${name}</b>`, adminPrice: (price) => `💰 Бағасы: <b>${price}</b>`,
  adminDays: (days) => `📅 Күн: <b>${days}</b>`, adminConfirmQ: 'Растайсыз ба?',
  adminApproveBtn: '✅ Растау', adminRejectBtn: '❌ Бас тарту',
  adminNotAdmin: 'Сіз әкімші емессіз!', adminNotFound: 'Табылмады',
  adminAlreadyApproved: 'Қазірдің өзінде расталған!', adminApproved: 'Расталды!',
  adminApprovedMsg: (days) => `✅ Төлем расталды! ${days} күн қосылды.`,
  adminAlreadyProcessed: 'Қазірдің өзінде өңделген', adminRejected: 'Бас тартылды',
  adminRejectedMsg: '❌ Төлем бас тартылды.',
  memberApproved: (name, days) => `🎉 <b>Құттықтаймыз, ${name}!</b>\n\nТөлеміңіз әкімші тарапынан расталды.\nАккаунтыңызға <b>${days} күн</b> қосылды.\nЕнді бас мәзірден QR Pass алуыңызға болады!`,
  memberRejected: `⚠️ <b>Төлем қабылданбады!</b>\nӘкімші төлеміңізді бас тартты. Қайта көріңіз немесе әкімшімен байланысыңыз.`,
  contactTitle: '📞 <b>Байланыс ақпараты</b>', contactHours: 'Жұмыс уақыты:',
  contactWeekdays: '⏰ Дүйсенбі – Сенбі: 07:00 – 22:00', contactSunday: '⏰ Жексенбі: Демалыс',
  contactTelegram: (user) => `📱 Telegram: ${user}`, contactPhone: (phone) => `📞 Телефон: ${phone}`,
  contactNote: 'Сұрақтарыңыз болса, кез келген уақытта жазыңыз!', contactWriteBtn: '📱 Жазу',
  notRegisteredCb: 'Сіз тіркелмегенсіз. /start басыңыз',
  notRegisteredText: 'Алдымен /start командасын жіберіп тіркеліңіз.',
  fallback: '👋 Төмендегі мәзір түймелерін пайдаланыңыз:',
  langSwitchPrompt: '🌐 <b>Тілді таңдаңыз:</b>',
  langSwitchUz: '🇺🇿 O\'zbekcha', langSwitchRu: '🇷🇺 Русский',
  langSwitchKk: '🇰🇿 Қазақша', langSwitchEn: '🇬🇧 English',
  langSwitched: '✅ Тіл: Қазақша',
  frozenMsg: '❄️ Абонементіңіз мұздатылған. Менеджерге хабарласыңыз.',
};

const en = {
  welcome: `<b>Welcome!</b>\nRegister to access the GymSystem gym.\n\nPlease tap the button below to share your phone number.`,
  sharePhoneBtn: '📞 Share Phone Number',
  registered: (name) => `✅ <b>Great, ${name}!</b> You have registered successfully.\n\nYou don't have a subscription yet. Use the menu below to purchase one.`,
  menuCode: '🔑 Entry Code', menuQr: '🎫 Get QR Pass', menuAccount: '📊 My Account', menuHistory: '📅 Visit History',
  entryCodeMsg: (code, left, name) => `🔑 <b>Your entry code:</b>\n\n<code>${code}</code>\n\n👤 ${name}\n⏳ Remaining: ${left} days\n\n<i>This code is valid today only.\nTell it to the manager or enter it at the kiosk.</i>`,
  menuBuy: '💳 Buy Subscription', menuContact: '📞 Contact', menuRefresh: '🔄 Refresh',
  menuLang: '🌐 Til / Language', menuScan: '📸 Scan QR to enter',
  scanWrongGym: (got, expected) => `❌ This QR belongs to another gym (@${got}). Scan the QR for your @${expected} bot.`,
  scanInvalid: '❌ QR did not match. Please scan the wall check-in QR.',
  mainMenuGreeting: (name) => `Hello, <b>${name}</b>! 👋`,
  mainMenuSub: (left, total) => `Subscription: <b>${left} / ${total} training days</b>`,
  mainMenuPlan: (plan) => `🏅 Plan: <b>${plan}</b>`,
  mainMenuExpired: '🔴 <i>Your subscription has expired!</i>',
  mainMenuWarning: (left) => `⚠️ <i>Warning! Only ${left} days left!</i>`,
  mainMenuChoose: 'Choose a section:',
  qrExpired: `🔴 <b>Subscription expired!</b>\n\nGym access denied.\nPlease purchase a new subscription.`,
  qrBuyBtn: '💳 Buy Subscription',
  qrCaption: (name, left, plan) => `🎫 <b>${name}'s QR Pass</b>\n\nRemaining: <b>${left} training days</b>\n🏅 Plan: <b>${plan}</b>\n\n⏱ <i>QR code is valid for 5 minutes.\nHold it in front of the scanner.</i>`,
  accountTitle: '📊 <b>Your Profile</b>',
  accountName: (name) => `👤 Name: <b>${name}</b>`, accountPlan: (plan) => `🏅 Plan: <b>${plan}</b>`,
  accountTotal: (total) => `📦 Total subscription: <b>${total} days</b>`,
  accountUsed: (used) => `✔️ Used: <b>${used}</b>`, accountLeft: (left) => `⏳ Remaining: <b>${left}</b>`,
  accountStatusActive: 'Active', accountStatusExpired: 'Expired',
  accountStatus: (emoji, text) => `${emoji} Status: <b>${text}</b>`,
  historyTitle: '📅 <b>Visit History</b>',
  historyEmpty: '<i>No visits yet.\nStart your first workout! 💪</i>',
  historyTotal: (n) => `✔️ Total visits: <b>${n}</b>`,
  historyDaysLeft: (left) => `⏳ Days remaining: <b>${left}</b>`,
  buyTitle: '💳 <b>Buy Subscription</b>',
  buyEmpty: '💳 <b>Buy Subscription</b>\n\nNo plans available at the moment.',
  buyChoose: 'Choose a plan:', buyDays: 'days',
  payTitle: '💳 <b>Payment</b>', payPlan: 'Plan',
  payDuration: (days) => `📅 Duration: <b>${days} training days</b>`,
  payPrice: (price) => `💰 Price: <b>${price}</b>`,
  payChooseMethod: 'Choose payment method:',
  payCash: '💸 I paid cash', payOnline: '💳 I paid online (Payme/Click)',
  payBack: '◀️ Back', payPlanNotFound: 'Plan not found.',
  cashCreated: (refId) => `✅ <b>Request #${refId} received!</b>\n\nThe administrator will review and confirm.\nWe'll notify you about the result.`,
  onlineInstructions: (planName, price, gymName) => `💳 <b>Online Payment</b>\n\n📦 ${planName} — <b>${price}</b>\n\nPayment methods:\n💚 Payme — pay via the app\n🔵 Click — pay via the app\n\nAmount: <b>${price}</b>\nRecipient: <b>${gymName}</b>\n\n⬇️ <b>After payment, send a photo of the receipt to this chat!</b>`,
  receiptReceived: (refId) => `✅ <b>Receipt received!</b>\n\nRequest number: <b>#${refId}</b>\nThe administrator will review and confirm.\nWe'll notify you about the result.`,
  sendReceipt: 'After payment, send a photo of the receipt',
  adminNewPayment: '💰 <b>New Payment Request</b>',
  adminMember: (name) => `👤 Member: <b>${name}</b>`, adminPhone: (phone) => `📞 Phone: <b>${phone}</b>`,
  adminPlan: (emoji, name) => `${emoji} Plan: <b>${name}</b>`, adminPrice: (price) => `💰 Price: <b>${price}</b>`,
  adminDays: (days) => `📅 Days: <b>${days}</b>`, adminConfirmQ: 'Confirm?',
  adminApproveBtn: '✅ Approve', adminRejectBtn: '❌ Reject',
  adminNotAdmin: 'You are not an admin!', adminNotFound: 'Not found',
  adminAlreadyApproved: 'Already approved!', adminApproved: 'Approved!',
  adminApprovedMsg: (days) => `✅ Payment approved! ${days} days added.`,
  adminAlreadyProcessed: 'Already processed', adminRejected: 'Rejected',
  adminRejectedMsg: '❌ Payment rejected.',
  memberApproved: (name, days) => `🎉 <b>Congratulations, ${name}!</b>\n\nYour payment has been confirmed by the administrator.\n<b>${days} days</b> have been added to your account.\nYou can now get your QR Pass from the main menu!`,
  memberRejected: `⚠️ <b>Payment declined!</b>\nThe administrator declined your payment. Please try again or contact the administrator.`,
  contactTitle: '📞 <b>Contact Information</b>', contactHours: 'Working hours:',
  contactWeekdays: '⏰ Monday – Saturday: 07:00 – 22:00', contactSunday: '⏰ Sunday: Day off',
  contactTelegram: (user) => `📱 Telegram: ${user}`, contactPhone: (phone) => `📞 Phone: ${phone}`,
  contactNote: 'If you have questions, feel free to reach out anytime!', contactWriteBtn: '📱 Write',
  notRegisteredCb: "You're not registered. Press /start",
  notRegisteredText: 'Please send /start first to register.',
  fallback: '👋 Use the menu buttons below:',
  langSwitchPrompt: '🌐 <b>Choose language:</b>',
  langSwitchUz: '🇺🇿 O\'zbekcha', langSwitchRu: '🇷🇺 Русский',
  langSwitchKk: '🇰🇿 Қазақша', langSwitchEn: '🇬🇧 English',
  langSwitched: '✅ Language: English',
  frozenMsg: '❄️ Your subscription is frozen. Please contact the manager.',
};

module.exports = { uz, ru, kk, en };
